FROM golang:1.13.15-alpine3.12
RUN  mkdir /app
WORKDIR /app
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a 
EXPOSE 8080
ENTRYPOINT ["/app/GoHystrixDemo"]